version: '2'
services:
    samplemonolithicapp-app:
        image: samplemonolithicapp
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://samplemonolithicapp-mysql:3306/samplemonolithicapp?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=samplemonolithicapp-elasticsearch:9300
        ports:
            - 8080:8080
    samplemonolithicapp-mysql:
        extends:
            file: mysql.yml
            service: samplemonolithicapp-mysql
    samplemonolithicapp-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: samplemonolithicapp-elasticsearch
